version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: custoflow_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: custoflow
      MYSQL_USER: custoflow
      MYSQL_PASSWORD: custoflowpass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: custoflow_backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://custoflow:custoflowpass@db:3306/custoflow"
      APP_ENV: dev
    depends_on:
      - db
    ports:
      - "8000:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: custoflow_frontend
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: ["/usr/local/bin/docker-entrypoint.sh"]

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: custoflow_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: custoflow
      PMA_PASSWORD: custoflowpass
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db-data:
