version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: telution_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: telution
      MYSQL_USER: telution
      MYSQL_PASSWORD: telutionpass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: telution_backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://telution:telutionpass@db:3306/telution"
      APP_ENV: dev
    depends_on:
      - db
    ports:
      - "8000:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: telution_frontend
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  db-data:
